"""Contratti dati di N-Truth. Tutto il resto del sistema dipende solo da qui."""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

from ntruth.schemas.claims import (
    AdequacyAxis,
    ClaimAssumption,
    ClaimType,
    ConditionalBranch,
    ConditionalClaimOutput,
    DerivedClaim,
    DerivedClaimSet,
    DesignAdequacyFinding,
    IrrelevantPredicate,
    ReportResolutionState,
    RuleTraceEntry,
    aggregate_report_resolution,
)
from ntruth.schemas.core import (
    AlertClass,
    CellRef,
    Confidence,
    Determinability,
    DeterminabilityState,
    EvidenceSpan,
    EvidenceType,
    FrozenModel,
    NTruthModel,
    Provenance,
    ProvenanceKind,
    Severity,
    content_checksum,
    stable_id,
)
from ntruth.schemas.document import (
    DESIGN_RELEVANT_SECTIONS,
    DocumentIR,
    EvidenceTier,
    Paragraph,
    ParserStatus,
    Section,
    SectionRole,
    SourceFile,
    StatisticalCodeArtifact,
    StatisticalCodeCandidate,
    StatisticalCodeLanguage,
    Table,
)
from ntruth.schemas.experiment import (
    COUNT_KIND_V8_WIRE,
    Alert,
    ConditionalScenario,
    Contradiction,
    Contrast,
    Correction,
    CorrectionReason,
    CountKind,
    CountQuantifier,
    CountRecord,
    CountScope,
    DataSufficiency,
    Endpoint,
    Estimand,
    ExclusionPhase,
    ExclusionRecord,
    ExperimentBlock,
    Factor,
    GraphAlternativeConsequence,
    GraphStatus,
    Hierarchy,
    Inferability,
    InferenceTarget,
    InferenceTargetStatus,
    LifecycleStatus,
    NKind,
    NScope,
    NStatement,
    PlausibleGraphAlternative,
    PlausibleGraphSet,
    ProcessFact,
    Question,
    RiskLabel,
    StatisticalModelFact,
    TriState,
    UnitAssessment,
    Versions,
)
from ntruth.schemas.graph import (
    BIOLOGICAL_SOURCE_TYPES,
    CLUSTER_TYPES,
    CONTAINMENT_RANK,
    TECHNICAL_TYPES,
    GraphNode,
    GraphRelation,
    GraphViolation,
    NodeType,
    RelationType,
    make_node_id,
    make_relation_id,
    rank_of,
)
from ntruth.schemas.kernel import (
    ESTIMAND_UNSUPPORTED_OR_UNSPECIFIED,
    AuthorityType,
    BackboneRecord,
    BlockBoundaryRecord,
    BlockBoundaryStatus,
    ChallengeSourceClass,
    ConditionRecord,
    ConfirmationEvent,
    ConflictRecord,
    ConflictStatus,
    ContaminationAttestation,
    ContaminationExposureAssessment,
    CountScopeStatus,
    EventTiming,
    EvidenceBasis,
    ExposureAssessment,
    ExposureContainer,
    ExposurePathway,
    InferentialQuery,
    InterferenceStatus,
    KnowledgeState,
    KnowledgeValue,
    ProfileCoverageStatement,
    ProfileCoverageStatus,
    RuleChallenge,
    RuleChallengeStatus,
    ScenarioCoverage,
    ScenarioCoverageStatus,
    SensitivityRecord,
    SourceClass,
    SupportGrade,
    TextExposureRisk,
    TimingRelation,
    V8CountRecord,
)
from ntruth.schemas.manifest import (
    AssetStatus,
    BundleFileReference,
    BundleFileRole,
    ExperimentBundleManifest,
    FileToSampleMapping,
    LicenseManifest,
    LicenseTier,
    ProjectFile,
    ProjectManifest,
    ReleaseProfile,
)
from ntruth.schemas.rules import (
    PremiseTrace,
    Rule,
    RuleEvaluation,
    RuleFixture,
    RuleFixtureKind,
    RuleOutcome,
    Ruleset,
    normalize_predicate,
)

if TYPE_CHECKING:
    from ntruth.schemas.report import (
        BlockSummary,
        DomainTransparency,
        DomainValidationStatus,
        Report,
    )

_LAZY_REPORT_EXPORTS = frozenset(
    {"BlockSummary", "DomainTransparency", "DomainValidationStatus", "Report"}
)


def __getattr__(name: str) -> Any:
    """Carica i contratti di report senza creare il ciclo design -> schemas.

    Importare una sottoclasse come ``ntruth.schemas.core`` esegue prima questo
    package. Il report dipende dal compilatore di design, che a sua volta usa i
    contratti core: un import eager renderebbe quindi ``ntruth.reporting`` non
    importabile in un processo pulito.
    """

    if name not in _LAZY_REPORT_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module("ntruth.schemas.report"), name)
    globals()[name] = value
    return value


__all__ = [
    "BIOLOGICAL_SOURCE_TYPES",
    "CLUSTER_TYPES",
    "CONTAINMENT_RANK",
    "COUNT_KIND_V8_WIRE",
    "DESIGN_RELEVANT_SECTIONS",
    "ESTIMAND_UNSUPPORTED_OR_UNSPECIFIED",
    "TECHNICAL_TYPES",
    "AdequacyAxis",
    "Alert",
    "AlertClass",
    "AssetStatus",
    "AuthorityType",
    "BackboneRecord",
    "BlockBoundaryRecord",
    "BlockBoundaryStatus",
    "BlockSummary",
    "BundleFileReference",
    "BundleFileRole",
    "CellRef",
    "ChallengeSourceClass",
    "ClaimAssumption",
    "ClaimType",
    "ConditionRecord",
    "ConditionalBranch",
    "ConditionalClaimOutput",
    "ConditionalScenario",
    "Confidence",
    "ConfirmationEvent",
    "ConflictRecord",
    "ConflictStatus",
    "ContaminationAttestation",
    "ContaminationExposureAssessment",
    "Contradiction",
    "Contrast",
    "Correction",
    "CorrectionReason",
    "CountKind",
    "CountQuantifier",
    "CountRecord",
    "CountScope",
    "CountScopeStatus",
    "DataSufficiency",
    "DerivedClaim",
    "DerivedClaimSet",
    "DesignAdequacyFinding",
    "Determinability",
    "DeterminabilityState",
    "DocumentIR",
    "DomainTransparency",
    "DomainValidationStatus",
    "Endpoint",
    "Estimand",
    "EventTiming",
    "EvidenceBasis",
    "EvidenceSpan",
    "EvidenceTier",
    "EvidenceType",
    "ExclusionPhase",
    "ExclusionRecord",
    "ExperimentBlock",
    "ExperimentBundleManifest",
    "ExposureAssessment",
    "ExposureContainer",
    "ExposurePathway",
    "Factor",
    "FileToSampleMapping",
    "FrozenModel",
    "GraphAlternativeConsequence",
    "GraphNode",
    "GraphRelation",
    "GraphStatus",
    "GraphViolation",
    "Hierarchy",
    "Inferability",
    "InferenceTarget",
    "InferenceTargetStatus",
    "InferentialQuery",
    "InterferenceStatus",
    "IrrelevantPredicate",
    "KnowledgeState",
    "KnowledgeValue",
    "LicenseManifest",
    "LicenseTier",
    "LifecycleStatus",
    "NKind",
    "NScope",
    "NStatement",
    "NTruthModel",
    "NodeType",
    "Paragraph",
    "ParserStatus",
    "PlausibleGraphAlternative",
    "PlausibleGraphSet",
    "PremiseTrace",
    "ProcessFact",
    "ProfileCoverageStatement",
    "ProfileCoverageStatus",
    "ProjectFile",
    "ProjectManifest",
    "Provenance",
    "ProvenanceKind",
    "Question",
    "RelationType",
    "ReleaseProfile",
    "Report",
    "ReportResolutionState",
    "RiskLabel",
    "Rule",
    "RuleChallenge",
    "RuleChallengeStatus",
    "RuleEvaluation",
    "RuleFixture",
    "RuleFixtureKind",
    "RuleOutcome",
    "RuleTraceEntry",
    "Ruleset",
    "ScenarioCoverage",
    "ScenarioCoverageStatus",
    "Section",
    "SectionRole",
    "SensitivityRecord",
    "Severity",
    "SourceClass",
    "SourceFile",
    "StatisticalCodeArtifact",
    "StatisticalCodeCandidate",
    "StatisticalCodeLanguage",
    "StatisticalModelFact",
    "SupportGrade",
    "Table",
    "TextExposureRisk",
    "TimingRelation",
    "TriState",
    "UnitAssessment",
    "V8CountRecord",
    "Versions",
    "aggregate_report_resolution",
    "content_checksum",
    "make_node_id",
    "make_relation_id",
    "normalize_predicate",
    "rank_of",
    "stable_id",
]
