"""Contratti dati di N-Truth. Tutto il resto del sistema dipende solo da qui."""

from __future__ import annotations

from importlib import import_module
from typing import Any

from ntruth.schemas.adequacy import DesignAdequacyEvaluation, DesignAdequacyFinding
from ntruth.schemas.block_boundary import (
    BlockBoundaryChangeKind,
    BlockBoundaryCriterion,
    BlockBoundaryPredicate,
    BlockBoundaryStatus,
    BoundaryChangeReference,
    ExperimentBlockBoundaryChangeLedger,
    ExperimentBlockBoundaryChangeRecord,
    ExperimentBlockBoundaryRecord,
    InternalQueryRepresentability,
    append_experiment_block_boundary_change_ledger,
    build_experiment_block_boundary_change,
    build_experiment_block_boundary_change_ledger,
    verify_experiment_block_boundaries,
    verify_experiment_block_boundary_change_ledger,
)
from ntruth.schemas.causal_context import (
    QueryCausalContext,
    QueryCausalEventAggregate,
    TriState,
)
from ntruth.schemas.claims import (
    DerivedClaim,
    DerivedClaimSet,
    DeterminabilityState,
    IrrelevantPredicate,
    PredicateProofReference,
    ProfileCoverageReference,
    ProofTraceStep,
    ScientificReviewRequirement,
)
from ntruth.schemas.core import (
    AlertClass,
    CellRef,
    Confidence,
    Determinability,
    EvidenceSpan,
    EvidenceType,
    FrozenModel,
    NTruthModel,
    Provenance,
    ProvenanceKind,
    Severity,
    content_checksum,
    stable_id,
)
from ntruth.schemas.count_registry import (
    CANONICAL_COUNT_REGISTRY_VERSION,
    CanonicalCountKind,
    CanonicalCountRecord,
    CanonicalCountRegistry,
    CountCompatibility,
    CountInterval,
    CountLifecyclePhase,
    CountOrigin,
    CountQuantifier,
    CountScope,
    CountScopeIdentity,
    canonical_count_kind,
    count_compatibility,
    independent_n_presentation_alias,
)
from ntruth.schemas.coverage import (
    ProfileCoverageStatement,
    ScenarioCoverage,
    ScenarioCoverageStatus,
)
from ntruth.schemas.document import (
    DESIGN_RELEVANT_SECTIONS,
    DocumentIR,
    EvidenceTier,
    Paragraph,
    ParserStatus,
    Section,
    SectionRole,
    SourceFile,
    StatisticalCodeArtifact,
    StatisticalCodeCandidate,
    StatisticalCodeLanguage,
    Table,
)
from ntruth.schemas.events import (
    ApplicationEvent,
    AssignmentEvent,
    DesignEvent,
    EventRecord,
    EventRegistry,
    EventType,
    ExposureEvent,
    ObservationEvent,
    PoolEvent,
    RelativeTiming,
    SplitEvent,
    TemporalRelation,
)
from ntruth.schemas.execution import ImplementationRulePin, V8ExecutionManifest
from ntruth.schemas.experiment import (
    Alert,
    ConditionalScenario,
    Contradiction,
    Contrast,
    Correction,
    CorrectionReason,
    CountKind,
    CountRecord,
    DataSufficiency,
    Endpoint,
    Estimand,
    ExclusionPhase,
    ExclusionRecord,
    ExperimentBlock,
    Factor,
    GraphAlternativeConsequence,
    GraphStatus,
    Hierarchy,
    Inferability,
    InferenceTarget,
    InferenceTargetStatus,
    LifecycleStatus,
    NKind,
    NScope,
    NStatement,
    PlausibleGraphAlternative,
    PlausibleGraphSet,
    ProcessFact,
    Question,
    RiskLabel,
    StatisticalModelFact,
    UnitAssessment,
    Versions,
)
from ntruth.schemas.graph import (
    BIOLOGICAL_SOURCE_TYPES,
    CLUSTER_TYPES,
    CONTAINMENT_RANK,
    TECHNICAL_TYPES,
    GraphNode,
    GraphRelation,
    GraphViolation,
    NodeType,
    RelationType,
    make_node_id,
    make_relation_id,
    rank_of,
)
from ntruth.schemas.graph_v8 import (
    V8ExperimentGraph,
    V8GraphNode,
    V8GraphNodeType,
    V8GraphRelation,
    V8GraphRelationType,
)
from ntruth.schemas.kernel import (
    KERNEL_SCHEMA_VERSION,
    KernelIdentity,
    KernelModel,
    kernel_json_schemas,
    write_kernel_json_schemas,
)
from ntruth.schemas.knowledge import KnowledgeState, KnowledgeValue
from ntruth.schemas.manifest import (
    AssetStatus,
    BundleFileReference,
    BundleFileRole,
    ExperimentBundleManifest,
    FileToSampleMapping,
    LicenseManifest,
    LicenseTier,
    ProjectFile,
    ProjectManifest,
)
from ntruth.schemas.prospective import (
    ConfirmationRelationKind,
    ConfirmationTarget,
    DeviationRecord,
    DeviationType,
    ExecutedDesignRecord,
    ExecutedInputLedger,
    PlanExecutionReconciliation,
    PlannedDesignRecord,
    ProspectiveArtifact,
    ProspectiveArtifactKind,
    ProspectiveInputLedger,
    ProspectiveInputScientificReviewRequired,
    ReconciliationStatus,
    SupportBindingScope,
    SupportEvidenceBinding,
    build_executed_design,
    build_executed_input_ledger,
    build_planned_design,
    build_prospective_artifact,
    build_prospective_input_ledger,
    reconcile_plan_execution,
)
from ntruth.schemas.query import InferentialQuery
from ntruth.schemas.report_resolution import (
    ReportResolutionOutcome,
    ReportResolutionPolicy,
    ReportResolutionState,
    TrivialExplicitReportResolutionPolicy,
)
from ntruth.schemas.rules import (
    Rule,
    RuleEvaluation,
    RuleFixture,
    RuleFixtureKind,
    RuleOutcome,
    Ruleset,
    normalize_predicate,
)
from ntruth.schemas.schema_snapshot import (
    KernelSchemaSnapshot,
    build_kernel_schema_snapshot,
    load_installed_kernel_schema_snapshot,
    load_kernel_schema_snapshot_file,
)
from ntruth.schemas.support import (
    SOURCE_CLASS_REGISTRY_ID,
    SUPPORT_GRADE_VOCABULARY_APPENDIX_R_1,
    SUPPORT_GRADE_VOCABULARY_SECTION_0_4,
    AuthorityType,
    ConfirmationEvent,
    EpistemicEventLedger,
    EvidenceBasis,
    EvidenceRecord,
    EvidenceTypeV8,
    RuleChallenge,
    RuleChallengeDecision,
    RuleChallengeDecisionOutcome,
    RuleChallengeStatus,
    ScientificReviewStatus,
    SensitivityRecord,
    SourceClassRef,
    SourceContext,
    SourceRecord,
    SupportDescriptor,
    SupportGrade,
)

_LAZY_MODULE_EXPORTS: dict[str, str] = {
    name: "ntruth.schemas.report"
    for name in (
        "BlockSummary",
        "DomainTransparency",
        "DomainValidationStatus",
        "Report",
    )
} | {
    name: "ntruth.schemas.report_bundle"
    for name in (
        "EXECUTED_EPISTEMIC_BOUNDARY",
        "PLANNED_EPISTEMIC_BOUNDARY",
        "RECONCILED_EPISTEMIC_BOUNDARY",
        "RETROSPECTIVE_EPISTEMIC_BOUNDARY",
        "ConflictRecord",
        "HandoffItem",
        "HandoffItemCategory",
        "HandoffItemOrigin",
        "QueryReportSection",
        "ReportBundle",
        "ReportDesignContext",
        "ReportDesignRecordContext",
        "ReportQuestion",
        "StatisticalHandoff",
        "StrategyModuleStatus",
        "VerifiedPipelineContext",
        "build_handoff_item",
        "build_report_bundle",
        "build_verified_pipeline_context",
        "epistemic_boundary_for_context",
        "explicit_absence",
        "resolve_report_claim_sets",
    )
}


def __getattr__(name: str) -> Any:
    """Carica i contratti di report/report_bundle senza creare cicli di import.

    Importare un sottomodulo (per esempio ``ntruth.schemas.core``) esegue prima
    questo package. ``report`` dipende dal compilatore di design, che a sua
    volta usa i contratti core, e ``report_bundle`` raggiunge il runtime del
    parser AI e la pipeline v8: un import eager renderebbe quindi non
    importabili in un processo pulito sia ``ntruth.reporting`` sia
    ``ntruth.graph``/``ntruth.rules`` senza il runtime AI.
    """

    module_name = _LAZY_MODULE_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value


__all__ = [
    "BIOLOGICAL_SOURCE_TYPES",
    "CANONICAL_COUNT_REGISTRY_VERSION",
    "CLUSTER_TYPES",
    "CONTAINMENT_RANK",
    "DESIGN_RELEVANT_SECTIONS",
    "EXECUTED_EPISTEMIC_BOUNDARY",
    "KERNEL_SCHEMA_VERSION",
    "PLANNED_EPISTEMIC_BOUNDARY",
    "RECONCILED_EPISTEMIC_BOUNDARY",
    "RETROSPECTIVE_EPISTEMIC_BOUNDARY",
    "SOURCE_CLASS_REGISTRY_ID",
    "SUPPORT_GRADE_VOCABULARY_APPENDIX_R_1",
    "SUPPORT_GRADE_VOCABULARY_SECTION_0_4",
    "TECHNICAL_TYPES",
    "Alert",
    "AlertClass",
    "ApplicationEvent",
    "AssetStatus",
    "AssignmentEvent",
    "AuthorityType",
    "BlockBoundaryChangeKind",
    "BlockBoundaryCriterion",
    "BlockBoundaryPredicate",
    "BlockBoundaryStatus",
    "BlockSummary",
    "BoundaryChangeReference",
    "BundleFileReference",
    "BundleFileRole",
    "CanonicalCountKind",
    "CanonicalCountRecord",
    "CanonicalCountRegistry",
    "CellRef",
    "ConditionalScenario",
    "Confidence",
    "ConfirmationEvent",
    "ConfirmationRelationKind",
    "ConfirmationTarget",
    "ConflictRecord",
    "Contradiction",
    "Contrast",
    "Correction",
    "CorrectionReason",
    "CountCompatibility",
    "CountInterval",
    "CountKind",
    "CountLifecyclePhase",
    "CountOrigin",
    "CountQuantifier",
    "CountRecord",
    "CountScope",
    "CountScopeIdentity",
    "DataSufficiency",
    "DerivedClaim",
    "DerivedClaimSet",
    "DesignAdequacyEvaluation",
    "DesignAdequacyFinding",
    "DesignEvent",
    "Determinability",
    "DeterminabilityState",
    "DeviationRecord",
    "DeviationType",
    "DocumentIR",
    "DomainTransparency",
    "DomainValidationStatus",
    "Endpoint",
    "EpistemicEventLedger",
    "Estimand",
    "EventRecord",
    "EventRegistry",
    "EventType",
    "EvidenceBasis",
    "EvidenceRecord",
    "EvidenceSpan",
    "EvidenceTier",
    "EvidenceType",
    "EvidenceTypeV8",
    "ExclusionPhase",
    "ExclusionRecord",
    "ExecutedDesignRecord",
    "ExecutedInputLedger",
    "ExperimentBlock",
    "ExperimentBlockBoundaryChangeLedger",
    "ExperimentBlockBoundaryChangeRecord",
    "ExperimentBlockBoundaryRecord",
    "ExperimentBundleManifest",
    "ExposureEvent",
    "Factor",
    "FileToSampleMapping",
    "FrozenModel",
    "GraphAlternativeConsequence",
    "GraphNode",
    "GraphRelation",
    "GraphStatus",
    "GraphViolation",
    "HandoffItem",
    "HandoffItemCategory",
    "HandoffItemOrigin",
    "Hierarchy",
    "ImplementationRulePin",
    "Inferability",
    "InferenceTarget",
    "InferenceTargetStatus",
    "InferentialQuery",
    "InternalQueryRepresentability",
    "IrrelevantPredicate",
    "KernelIdentity",
    "KernelModel",
    "KernelSchemaSnapshot",
    "KnowledgeState",
    "KnowledgeValue",
    "LicenseManifest",
    "LicenseTier",
    "LifecycleStatus",
    "NKind",
    "NScope",
    "NStatement",
    "NTruthModel",
    "NodeType",
    "ObservationEvent",
    "Paragraph",
    "ParserStatus",
    "PlanExecutionReconciliation",
    "PlannedDesignRecord",
    "PlausibleGraphAlternative",
    "PlausibleGraphSet",
    "PoolEvent",
    "PredicateProofReference",
    "ProcessFact",
    "ProfileCoverageReference",
    "ProfileCoverageStatement",
    "ProjectFile",
    "ProjectManifest",
    "ProofTraceStep",
    "ProspectiveArtifact",
    "ProspectiveArtifactKind",
    "ProspectiveInputLedger",
    "ProspectiveInputScientificReviewRequired",
    "Provenance",
    "ProvenanceKind",
    "QueryCausalContext",
    "QueryCausalEventAggregate",
    "QueryReportSection",
    "Question",
    "ReconciliationStatus",
    "RelationType",
    "RelativeTiming",
    "Report",
    "ReportBundle",
    "ReportDesignContext",
    "ReportDesignRecordContext",
    "ReportQuestion",
    "ReportResolutionOutcome",
    "ReportResolutionPolicy",
    "ReportResolutionState",
    "RiskLabel",
    "Rule",
    "RuleChallenge",
    "RuleChallengeDecision",
    "RuleChallengeDecisionOutcome",
    "RuleChallengeStatus",
    "RuleEvaluation",
    "RuleFixture",
    "RuleFixtureKind",
    "RuleOutcome",
    "Ruleset",
    "ScenarioCoverage",
    "ScenarioCoverageStatus",
    "ScientificReviewRequirement",
    "ScientificReviewStatus",
    "Section",
    "SectionRole",
    "SensitivityRecord",
    "Severity",
    "SourceClassRef",
    "SourceContext",
    "SourceFile",
    "SourceRecord",
    "SplitEvent",
    "StatisticalCodeArtifact",
    "StatisticalCodeCandidate",
    "StatisticalCodeLanguage",
    "StatisticalHandoff",
    "StatisticalModelFact",
    "StrategyModuleStatus",
    "SupportBindingScope",
    "SupportDescriptor",
    "SupportEvidenceBinding",
    "SupportGrade",
    "Table",
    "TemporalRelation",
    "TriState",
    "TrivialExplicitReportResolutionPolicy",
    "UnitAssessment",
    "V8ExecutionManifest",
    "V8ExperimentGraph",
    "V8GraphNode",
    "V8GraphNodeType",
    "V8GraphRelation",
    "V8GraphRelationType",
    "VerifiedPipelineContext",
    "Versions",
    "append_experiment_block_boundary_change_ledger",
    "build_executed_design",
    "build_executed_input_ledger",
    "build_experiment_block_boundary_change",
    "build_experiment_block_boundary_change_ledger",
    "build_handoff_item",
    "build_kernel_schema_snapshot",
    "build_planned_design",
    "build_prospective_artifact",
    "build_prospective_input_ledger",
    "build_report_bundle",
    "build_verified_pipeline_context",
    "canonical_count_kind",
    "content_checksum",
    "count_compatibility",
    "epistemic_boundary_for_context",
    "explicit_absence",
    "independent_n_presentation_alias",
    "kernel_json_schemas",
    "load_installed_kernel_schema_snapshot",
    "load_kernel_schema_snapshot_file",
    "make_node_id",
    "make_relation_id",
    "normalize_predicate",
    "rank_of",
    "reconcile_plan_execution",
    "resolve_report_claim_sets",
    "stable_id",
    "verify_experiment_block_boundaries",
    "verify_experiment_block_boundary_change_ledger",
    "write_kernel_json_schemas",
]
