"""Contratto stabile del parser AI; nessun modello o rete inclusi."""

from ntruth.parser_ai.adapter import ParserAIAdapter, run_parser_adapter
from ntruth.parser_ai.contract import (
    PARSER_AI_CONTRACT_VERSION,
    CandidateAlternative,
    CandidateContrast,
    CandidateEdge,
    CandidateEndpoint,
    CandidateEstimand,
    CandidateExperimentBlock,
    CandidateFactor,
    CandidateNode,
    ClarificationQuestion,
    DeterminabilityAssessment,
    NodeOntologyValue,
    ParserAIDocumentInput,
    ParserAIEvidenceSpan,
    ParserAIInput,
    ParserAIModelMetadata,
    ParserAIOutput,
    ParserAISectionInput,
    ParserAITableInput,
    RelationOntologyValue,
    parser_ai_json_schemas,
    validate_contract_pair,
)

__all__ = [
    "PARSER_AI_CONTRACT_VERSION",
    "CandidateAlternative",
    "CandidateContrast",
    "CandidateEdge",
    "CandidateEndpoint",
    "CandidateEstimand",
    "CandidateExperimentBlock",
    "CandidateFactor",
    "CandidateNode",
    "ClarificationQuestion",
    "DeterminabilityAssessment",
    "NodeOntologyValue",
    "ParserAIAdapter",
    "ParserAIDocumentInput",
    "ParserAIEvidenceSpan",
    "ParserAIInput",
    "ParserAIModelMetadata",
    "ParserAIOutput",
    "ParserAISectionInput",
    "ParserAITableInput",
    "RelationOntologyValue",
    "parser_ai_json_schemas",
    "run_parser_adapter",
    "validate_contract_pair",
]
