"""Supervision, authority, licence, and use-policy enums."""

from __future__ import annotations

from enum import StrEnum


class SupervisionSource(StrEnum):
    HUMAN_PUBLIC = "HUMAN_PUBLIC"
    STRUCTURED_METADATA = "STRUCTURED_METADATA"
    WEAK_RULE = "WEAK_RULE"
    SYNTHETIC = "SYNTHETIC"


class AuthorityLevel(StrEnum):
    AUXILIARY = "AUXILIARY"
    CANDIDATE = "CANDIDATE"
    NTRUTH_GOLD = "NTRUTH_GOLD"
    EXTERNAL_CHALLENGE_CANDIDATE = "EXTERNAL_CHALLENGE_CANDIDATE"


class LicenseStatus(StrEnum):
    VERIFIED = "VERIFIED"
    RESTRICTED = "RESTRICTED"
    UNKNOWN = "UNKNOWN"


class ExclusionReason(StrEnum):
    TOKEN_LABEL_LENGTH_MISMATCH = "TOKEN_LABEL_LENGTH_MISMATCH"
    INVALID_OFFSET = "INVALID_OFFSET"
    UNSUPPORTED_OVERLAPPING_SPANS = "UNSUPPORTED_OVERLAPPING_SPANS"
    UNKNOWN_LABEL = "UNKNOWN_LABEL"
    MISSING_SOURCE_IDENTITY = "MISSING_SOURCE_IDENTITY"
    MISSING_LEAKAGE_GROUP = "MISSING_LEAKAGE_GROUP"
    LICENSE_TRAINING_PROHIBITED = "LICENSE_TRAINING_PROHIBITED"
    LICENSE_UNKNOWN = "LICENSE_UNKNOWN"
    SPLIT_CONFLICT = "SPLIT_CONFLICT"
    TEST_TRAINING_ELIGIBLE = "TEST_TRAINING_ELIGIBLE"
    SILENT_TRUNCATION_ATTEMPT = "SILENT_TRUNCATION_ATTEMPT"
    INVALID_CHECKSUM = "INVALID_CHECKSUM"
    INCOMPLETE_LINEAGE = "INCOMPLETE_LINEAGE"
    EMPTY_RECORD = "EMPTY_RECORD"
    MALFORMED_SOURCE = "MALFORMED_SOURCE"
    UNMAPPED_LABEL = "UNMAPPED_LABEL"
    SYNTHETIC_FORBIDDEN = "SYNTHETIC_FORBIDDEN"
    OVERLAP_QUARANTINE = "OVERLAP_QUARANTINE"
